### PR TITLE
feat(number-input): add number input component

### PR DESCRIPTION
**Pull request by brian-patrick-3**
## Summary

Add Number Input component.

## ADO Story Link

https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1808763/?view=edit

### CODE REVIEW

**Comment by maulik-thaker1** [comment]
Input box is large as compare to UX. 
Screenshot 2024-07-30 at 5 52 43 PM

**Review by maulik-thaker1 — APPROVED** [review]
LGTM.

1. IMO we should include this inside form story as well.

**Comment by brian-patrick-3** [comment]
> Input box is large as compare to UX. Screenshot 2024-07-30 at 5 52 43 PM

That's just kind of how it is with auto width until the application controls the width of the host element.

**Pull request merged**
