### PR TITLE
feat: updated data table and tags skeleton pattern

### PR DESCRIPTION
**Pull request by kumarivijeta**
## Summary

Updated Data Table and Tags skeleton as per Figma

## ADO Story 
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1991926)

## Figma Link

https://www.figma.com/design/2Vgr8KRWwtJiCETolv0zNE/1.12-Rio-De-Janeiro?node-id=92-52399&node-type=instance&m=dev

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [x] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

## Screenshots

image

image

### CODE REVIEW

**Review by wbarbee — COMMENTED** [review]
@kumarivijeta this looks good. do we want to add a Skeleton variant to the Global Filter pattern as well?

**Comment by srpriyankashetty** [comment]
Hi @kumarivijeta .
Tag size is not changing as per small or medium.
Does the tag color and Shade attributes imply on skeleton when made changes?

**Review by brian-patrick-3 — APPROVED** [review]

**Review by kumarivijeta — COMMENTED** [review]
Hi @srpriyankashetty  
1.  Changing size of tag  medium to small and vice versa, Working as expected.
2. Changing tag color will not have impact on tag skeleton
3. As per figma we don't have checkbox selection for data table. Hence, removed.

**Pull request merged**
