### PR TITLE
feat(footer): color token update

### PR DESCRIPTION
**Pull request by kumarivijeta**
## Summary

Footer color token update

## ADO Story

[TASK 2003565](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003565)

## Figma Link

https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/branch/qMpff4GuFUEcsMUkvacS3U/Applications---Component-Library?node-id=20056-822964&m=dev

## Notes

Dependancy PR 
https://github.com/kyndryl-design-system/shidoka-foundation/pull/76

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

### CODE REVIEW

**Review by brian-patrick-3 — APPROVED** [review]
LGTM, though make a note that the Links don't pass contrast accessibility in Light mode.

**Review by srpriyankashetty — APPROVED** [review]
Verified and looks fine in both light and dark mode
Verified the footer changes in mobile view
image
image

**Pull request merged**
