### PR TITLE
feat(shidoka-icons): replaced carbon icons with shidoka icons

### PR DESCRIPTION
**Pull request by tulasigudibanda**
BREAKING CHANGE: replaced carbon icons with shidoka icons.

## ADO Story or GitHub Issue Link
https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1970520

## Figma Link
https://www.figma.com/design/ZNudJzPCnqRpzUEnDatcMb/Shidoka-Icon-Library?node-id=0-1&node-type=canvas&m=dev

## Notes

- replaced carbon icons with shidoka icons.

Notes for QA :
Certain icons are downsized in shidoka to look similar to carbon icons .  
Info icon looks less crisp in shidoka . 
Icon replacement variations due to unavailability of certain icons in shidoka : 
- overflow-menu--horizontal and overflow-menu--vertical icons are replaced with overflow icon
- misuse icon with  close-filled icon
- error--filled with warning-filled
- gender--male with user icon
- gender--female with user icon

### CODE REVIEW

**Comment by wbarbee** [comment]
just a couple of very minor sizing changes due to new icon sizing and the vertical alignment of icons on the number input. LGTM!

**Review by wbarbee — APPROVED** [review]

**Comment by tulasigudibanda** [comment]
> just a couple of very minor sizing changes due to new icon sizing and the vertical alignment of icons on the number input. LGTM!

Some icons are downsized to look similar to carbon icon. Fixed the alignment of number input

**Review by brian-patrick-3 — APPROVED** [review]

**Comment by srpriyankashetty** [comment]
Issue raised and the solution provided by Tulasi.

Bread crumb : We have only vertical overflow icon in shidoka . Brian told me to use it even in place of horizontal. Just checked again with Brian and changed the orientation. This takes care of all the components wherever it is present.
checkbox group - yes, info icon looks less crisp in shidoka. Pointed this earlier to Brian. He told me to check with UX. Diana has to get back. Applicable to all the components wherever it is present
Data table - Mapping variation due to unavailability of certain icons in shidoka  (added in the PR desc)
Data table - Batch Actions - matches with https://next--shidoka-applications.netlify.app/  which is correct
DT- Legend - Mapping variation - alignment fixed
Data table - Disable rows - matches with https://next--shidoka-applications.netlify.app/  which is correct
DT - Column setting, Notification, Tabs, Toggle button, Widget, Form default  -  alignment fixed.
DT - Column setting , Side drawer - border fixed 
Dropdown  - yes , some icons look different in shidoka
Stepper - circle-filled icon looks different in shidoka.

**Review by srpriyankashetty — APPROVED** [review]
Verified the Shidoka icons in Shidoka application.
Re- tested the specified issue and looks fine
Based on the Dev comment for few issues, considering will be fixed in upcoming changes.

**Pull request merged**
