### PR TITLE
feat(progress-bar): add hideLabel property

### PR DESCRIPTION
**Pull request by vrblymt**
## Summary

If label property is empty then it will hide the label container.

## Checklist

- [ ] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [ ] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

### CODE REVIEW

**Review by brian-patrick-3 — CHANGES_REQUESTED** [review]
The label is still required for accessibility purposes, even when hidden. This is why we use a separate prop to toggle visibility on other components like text input for example.

**Comment by vrblymt** [comment]
Do you want the hideLabel prop or it can detect if the label property is empty?

**Comment by brian-patrick-3** [comment]
> Do you want the hideLabel prop or it can detect if the label property is empty?

label prop is required and cannot be empty

**Comment by vrblymt** [comment]
> > Do you want the hideLabel prop or it can detect if the label property is empty?
> 
> label prop is required and cannot be empty

It can be an empty string. But I renamed the class name to sr-only.

**Comment by vrblymt** [comment]
hideLabel property added to component

**Review by brian-patrick-3 — APPROVED** [review]
LGTM!

To resolve conflicts in custom-elements,json:
1. Pull latest to `main` branch locally
2. `git merge main` to your branch
3. `npm run analyze` to generate new custom-elements.json
4. Stage file/accept conflict resolution
5. Complete merge

**Pull request merged**
