### PR TITLE
fix(form components): : dark mode token updates

### PR DESCRIPTION
**Pull request by wbarbee**
## Summary

Implement Dark Mode color tokens from updated Figma files for 2.0 Breaking Changes on the following components:

- [x] Checkbox -- (* check after Robert's new tokens are updated, may need to update checked base tokens)
- [x] Radio Button -- (* check after Robert's new tokens are updated)
- [x] Text Input
- [x] Text Area
- [x] Toggle Button
- [x] Dropdown -- (* check tags when tokens updated)
- [x] Number Input (* check +/- when button tokens updated)
- [x] Form Label

- [x] `form-input.scss`* (base styles for most form input components) -- check WARNING, check whether disabled labels should have styling

Form components that will be handled on a separate PR:
- [Date Picker](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003589)
- [Date Range Picker](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003590)
- [Timepicker](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003569)

## ADO Story or GitHub Issue Link

- [Checkbox](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003593)
- [Text Input](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003570)
- [Text Area](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003571)
- [Toggle Button](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003568)
- [Dropdown](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003587)
- [Number Input](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003582)
- [Radio Button](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003577)

## Figma Links

- [Checkbox](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=13336-80710&node-type=section&m=dev)
- [Text Input](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=4045-141810&node-type=canvas&m=dev)
- [Text Area](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=4285-236267&node-type=canvas&m=dev)
- [Toggle Button](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=4211-233454&node-type=instance&m=dev)
- [Dropdown](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=4161-101206&node-type=instance&m=dev)
- [Number Input](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=14893-233109&node-type=canvas&m=dev)
- [Radio Button](https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=4193-260552&node-type=symbol&m=dev)

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [x] Noted breaking changes (if any).
- [x] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [x] Added/updated Stories with controls to cover all variants.
- [x] Ran `test` locally to address any failures.
- [x] Added/updated the Figma link for the Story's Design tab.
- [x] Added any new component exports to the src/index.ts file

## Figma/Storybook Inconsistencies

- ~~thumb color on toggleButton hover in dark mode (`--kd-color-background-ui-hollow-default`):~~
- `Background/UI/Default/Secondary` (`--kd-color-background-ui-default-secondary`) -- not available in storybook/`tokens` (push requested from design team)
- ~~`Background/Container/Default` (`--kd-color-background-container-default`) doesn't match figma~~

## Testing Instructions
- all of these components should have a Storybook sidenav item, except for Form Label, that can be most easily checked in the `Patterns/Forms` story
- there are still a few inconsistencies in the colors as they appear in Figma vs. Storybook. i've noted all that i could find in the section above, but please make any notes of others that you might see. the tokens themselves should all be consistent between the code and the figma file, just not fully reflected yet in storybook

## Screenshots

(if any)

### CODE REVIEW

**Comment by srpriyankashetty** [comment]
Hi @wbarbee ,

1. The tooltips in the dark mode - shows with black or transparent background - is this expected?
2. The Figma links provided does not show the dark theme - are these just for reference? (just check for 2 checkbox and Text area)

image

**Comment by wbarbee** [comment]
> Hi @wbarbee ,
> 
> 1. The tooltips in the dark mode - shows with black or transparent background - is this expected?
> 2. The Figma links provided does not show the dark theme - are these just for reference? (just check for 2 checkbox and Text area)
> 
> image

hi @srpriyankashetty 

1. the tooltips and buttons will be updated separately as they are their own components
2. not all of the figma files have dark mode, we're just going off of the token values that they both share

thanks!

**Comment by srpriyankashetty** [comment]
In Dropdown 
Multi select, multi select searchable and Data driven options - The selected options text is not clearly visible due to font color in dark mode.
image
image

**Review by kumarivijeta — APPROVED** [review]

**Comment by wbarbee** [comment]
> In Dropdown Multi select, multi select searchable and Data driven options - The selected options text is not clearly visible due to font color in dark mode. image image

same thing here @srpriyankashetty. those are instances of the Tags component that will be styled correctly once those changes are merged in

**Review by brian-patrick-3 — APPROVED** [review]

**Review by srpriyankashetty — APPROVED** [review]
Verified Checkbox, Checkbox group and Checkbox subgroup looks fine in dark mode theme.
Verified Single, Single searchable, Multi select, Multi select searchable, Grouped and Data driven options dropdown looks fine in dark mode theme.
Verified the Number input in dark mode and looks fine
Verified the Toggle button in dark mode and looks fine.
Verified Text input and text input with icon in dark mode theme and looks fine.
Verified that Text Area looks fine in Dark mode theme.
Verified the Radio button and Radio button group in dark mode theme.

@wbarbee .
Just need clarification on the color of Radio button in dark mode - is this expected color?
The look and feel wise i feel its better if we have some lighter color.!
image

**Comment by wbarbee** [comment]
> Verified Checkbox, Checkbox group and Checkbox subgroup looks fine in dark mode theme. Verified Single, Single searchable, Multi select, Multi select searchable, Grouped and Data driven options dropdown looks fine in dark mode theme. Verified the Number input in dark mode and looks fine Verified the Toggle button in dark mode and looks fine. Verified Text input and text input with icon in dark mode theme and looks fine. Verified that Text Area looks fine in Dark mode theme. Verified the Radio button and Radio button group in dark mode theme.
> 
> @wbarbee . Just need clarification on the color of Radio button in dark mode - is this expected color? The look and feel wise i feel its better if we have some lighter color.! image

confirmed that this token, `--kd-color-background-button-secondary-state-default`, matches the checked color values from the radio button figma file. i'll double-check again when we make our final pass on these components. thank you!

**Pull request merged**
