### PR TITLE
feat(skeleton): added lines props for skeleton

### PR DESCRIPTION
**Pull request by kumarivijeta**
## Summary

-Added lines props into skeleton to provide more flexibility to use skeleton as multiple times.
  - lines(default  to 1) property control's how many number of skeleton to be shown

## ADO Story

[USER STORY 1995481](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1995481)

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [x] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [x] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

## Screenshots

image

image

### CODE REVIEW

**Review by brian-patrick-3 — CHANGES_REQUESTED** [review]
I don't think it's necessary to add min/max width props. We can just let applications control the width through CSS on the host tag.

**Review by brian-patrick-3 — APPROVED** [review]

**Review by srpriyankashetty — APPROVED** [review]
Verified the inline and multi-inline skeleton 
Verified the Block and multi-block skeleton
Verified adding more line and looks good
Verified the mobile view and looks fine
Verified the skeleton animation changing from grey to white.

**Pull request merged**
