### PR TITLE
fix(errorBlock): Added the vectorised error images

### PR DESCRIPTION
**Pull request by jaideep08**
## Summary

Replaced the error images with vectorised ones.

## ADO Story or GitHub Issue Link

[TASK 1973047](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1973047)

## Figma Link

https://www.figma.com/design/1VsTvlFDnpL5qOZRZ4ADvD/UXD_Kyn_Mascot_v2_10_2024?node-id=12-148820&node-type=section&t=WS7dRHKCi8oYo2GG-0

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [ ] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

## Screenshots

Screenshot 2024-10-25 at 4 29 08 PM

### CODE REVIEW

**Comment by brian-patrick-3** [comment]
Huge savings on file size, very nice. Surprised to see the drawings themselves have been updated too.

**Review by srpriyankashetty — APPROVED** [review]
Verified the images from Files changed and new images matches with Figma file.

**Pull request merged**
