### PR TITLE
fix(stepper): add support for link url values on stepper items

### PR DESCRIPTION
**Pull request by brian-patrick-3**
## Summary

A bug was raised that stepper item title links could not be controlled by the application. This PR accomplishes the following:

1. Added a component prop so a link href can be passed to stepper items/children.
2. Step Title will render as plain text if no link is provided.
3. Link href value added to click event details.
4. Child step items will now always be accessible/expandable even when the parent step is not in active state.

### CODE REVIEW

**Review by tulasigudibanda — APPROVED** [review]

**Review by marcosebastianlopez — APPROVED** [review]
This looks good, thank you for doing this.

**Comment by srpriyankashetty** [comment]
In case of Horizontal stepper, the boarder padding must be taken care when clicked for all the 4-link text, rest other pages looks fine.

image

**Comment by brian-patrick-3** [comment]
> In case of Horizontal stepper, the boarder padding must be taken care when clicked for all the 4-link text. 
> And the alignment between step number and the status is different for every status. Rest other pages look fine.
1. Added 1px padding to accommodate link focus outline.
2. first/last steps have left/right alignments, the rest are centered, as per the design.

**Review by srpriyankashetty — COMMENTED** [review]
Verified the link text in Horizontal stepper
Verified the link text in Vertical stepper
Verified the link text in Nested stepper
Verified that link is not provided for the step that are not completed
Verified that href is passed to stepper items/children.
Verified the Step Title renders as plain text if there is no link provided.
Verified the Link href value is added to click event details.
Verified that Child step items are now accessible/expandable even when the parent step is not in active state.
Verified the Stepper type Procured and status format

**Pull request merged**
