### PR TITLE
Various Enhancements for Global Filters

### LINKED ISSUE #64: Request for mutiselect dropdown with select all option
**Is your feature request related to a problem? Please describe.**
I need option of select All on drop down with multi select. on click of All option other options should be selected automatically.

image

### LINKED ISSUE #73: Request for Radio/Checkbox Group horizontal alignment option
**Is your feature request related to a problem? Please describe.**

Yes. I am using **kyn-radio-button-group** and by default the radio buttons are aligned vertically. Is there any way to align the radio buttons horizontally?

**Describe alternatives you've considered**
I tried over riding css but it doesn't work since the **fieldset** which holds this radio buttons is wrapped inside a **shadow-root**.

Can you please let me know if there is any way to align the radio buttons horizontally ?

**Additional context**

image

### PR DESCRIPTION
**Pull request by brian-patrick-3**
## Summary

Global Filter pattern dependencies.

- [x] Checkbox Group 
   - [x] Horizontal Alignment
      - resolves #73
   - [x] Hidden Legend
   - [x] Select All
   - [x] Filterable
   - [x] Show more/less
- [x] Radio Button Group - Horizontal Alignment 
- [x] Text Input - Hidden Label
- [x] Overflow Menu - Vertical Dots
- [x] Dropdown - Select All
   - resolves #64

### CODE REVIEW

**Review by maulik-thaker1 — APPROVED** [review]
LGTM. 

but one observation related to focus event I noticed on checkbox. 
for ex: here **Show less** / **Show More** button persist focus after click

Screenshot 2024-02-12 at 1 55 35 PM

I have doubt regarding branch merge. Earlier we are merging our **feature branch** to **beta** and then on **main**. So from now onwards are we directly merge our **feature branch** to **main** ?

**Comment by brian-patrick-3** [comment]
> One observation related to focus event I noticed on checkbox. for ex: here **Show less** / **Show More** button persist focus after click

I think this is the correct behavior.

> I have doubt regarding branch merge. Earlier we were merging our **feature branch** into **beta** and then on **main**. So from now onwards are we directly merge our **feature branch** to **main** ?

Yes beta is only needed for breaking changes now, or for tentative changes we want to test without releasing to stable.

**Comment by maulik-thaker1** [comment]
> > One observation related to focus event I noticed on checkbox. for ex: here **Show less** / **Show More** button persist focus after click
> 
> I think this is the correct behavior.
> 
> > I have doubt regarding branch merge. Earlier we were merging our **feature branch** into **beta** and then on **main**. So from now onwards are we directly merge our **feature branch** to **main** ?
> 
> Yes beta is only needed for breaking changes now, or for tentative changes we want to test without releasing to stable.

so we need to create our feature branch from **main** right ?

**Review by maulik-thaker1 — APPROVED** [review]

**Pull request merged**
