### PR TITLE
fix(bug-2044199): checkbox, checkboxGroup token updates/corrections

### PR DESCRIPTION
**Pull request by wbarbee**
## Summary (see screenshots below)

- [x] 1. The icon that is showing for Invalid text is in triangle shape, where as the Figma has circle
- [x] 2. The invalid text on disabling is not grayed out, just turns into black color
- [x] 3. The description is not grayed out on disabling
- [x] 4. Like caption the unselected checkbox color is changing when disabled.
- [x] 5. The parent checkbox is not showing in red, when has invalid text (issue is there in Production)

## ADO Story or GitHub Issue Link

[Bug 2044199](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2044199)

## Notes

- there were a few tokens that have been updated since the checkbox dark mode updates were merged into `next` that were causing these issues.
- need to confirm hover and focused state tokens for background, border, outline when disabled = false and invalid = true:
- [ ] unchecked
- [ ] checked
- [ ] parent partially checked (-)

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [x] Noted breaking changes (if any).
- [x] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [x] Added/updated Stories with controls to cover all variants.
- [x] Ran `test` locally to address any failures.
- [x] Added/updated the Figma link for the Story's Design tab.
- [x] Added any new component exports to the src/index.ts file

## Testing Instructions

Provide guidance to reviewers/testers here.

## Screenshots

1. The icon that is showing for Invalid text is in triangle shape, where as the Figma has circle
Screenshot 2024-12-16 at 10 03 37 AM

2. The invalid text on disabling is not grayed out, just turns into black color
3. The description is not grayed out on disabling
4. Like caption the unselected checkbox color is changing when disabled.
Screenshot 2024-12-16 at 10 11 01 AM

5. The parent checkbox is not showing in red, when has invalid text (issue is there in Production)
Screenshot 2024-12-16 at 9 56 23 AM

### CODE REVIEW

**Comment by srpriyankashetty** [comment]
Hi @wbarbee ,
On disable the checkbox are showing as below, can you please check.!
image

**Comment by wbarbee** [comment]
> Hi @wbarbee , On disable the checkbox are showing as below, can you please check.! image

this should be fixed on the deploy preview now, @srpriyankashetty. thank you

**Comment by wbarbee** [comment]
as noted above, i still need to confirm hover and focused state tokens for background, border, outline when disabled = false and invalid = true:
 - unchecked
 - checked
 - parent indeterminate
 
 this is otherwise ready to review

**Review by brian-patrick-3 — APPROVED** [review]

**Pull request merged**
